# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f97ffd033df2c7d3f55202331d6f0baf8d7514916c05dbe5c8547c694fc03eb27992ddabb381dba2e6a5a29da43b346075d76fda5dd9f639cbf1e5a53e787ce0

test:
  secret_key_base: 3962b01f57136e5bc7acf2399002998e9f1197fc034e8f3e34c39d2ef19c92bb9069d29f77c9a25ec48035b9ac26c716b30171e13851531d239276590448d860

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
